### ISSUE TITLE
Client side templates not stored

### ISSUE THREAD

**Issue by Swaagie** [bigpipe/pagelet#13]
Only the client side hash is stored on the pagelet instance, the actual client side template is not stored or send to the client. Meaning child pagelets that are re-rendered with some data result in `[object Object]`. If https://github.com/bigpipe/bigpipe.js/blob/master/pagelet.js#L176-L180 will call `render` with data, render will fluke due to https://github.com/bigpipe/bigpipe.js/blob/master/pagelet.js#L569 being `undefined` in stead of a `function`

Weird thing is the bigpipe.template object usually contains one template view function, unsure where that is coming from, there are no references in bigpipe.js.

Swapping the already parsed template with the data object is a simple fix, but doesn't allow the client to interact with the data and then re-render the template.

**Comment by 3rd-Eden** [comment]
@Swaagie didn't you resolve this?

**Comment by 3rd-Eden** [comment]
Client side pagelets work as intended.
